# Pytorch Turorual 01

## Linear Regression

In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
# 반복실행시 난수가 일정한 패턴을 유지하도록 설정
torch.manual_seed(777)

In [3]:
# X, Y tensor 데이터 정의
x_train = [[1],[2],[3]]
y_train = [[1],[2],[3]]
X = Variable(torch.Tensor(x_train))
Y = Variable(torch.Tensor(x_train))

In [4]:
# 선형회귀식 모형을 정의 (in feature : 1, out_feature : 1)

# Input  : 숫자 (N, in features) - element  x
# Output : 숫자 (N, out features) - 예측결과 ^y

# weight :   out_features x in_features
# bias   :   the learnable bias of the module of shape (out_features)

# in 1개, out 1개 : weight 1개 (in 1 * out 1), bias : 1개(out 1개)
model = nn.Linear(1,1,bias=True)  

    텐서플로의 경우 W와 b의 형식을 정의하고, 크기값도 맞춰야 한다
    W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
    b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [5]:
# http://pytorch.org/docs/master/nn.html
# cost 판단 함수 : 평균제곱 오차 ( Mean Squared Error )
# torch.nn.MSELoss(size_average=True)
criterion = nn.MSELoss()   

# Minimize :  Stochastic Gradient Descent (확률 활용 경사타고 내려가는 알고리즘)
# Learning Rate (경사타고내려가는 알고리즘의 학습단위) : 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

    .data  : 매개변수(ex> X,Y) , 함수객체(ex> cost) 뒤에 '.data'만 붙이면 내용을 바로 확인할 수 있다.

    [텐서플로] - tf.Session.run() 함수를 통해서만 학습 내용이 연산 및 확인가능
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for step in range(2001):
            sess.run(optimizer, feed_dict={X: x_data, Y: y_data})

In [6]:
# 학습모델 만들기
for step in range(2001):
    optimizer.zero_grad() # 학습 시작시 마다 기울기값 찾는 함수를 초기화
    
    # 지정한 가설로 학습시작
    hypothesis = model(X) # X (input data) 를 가설모형에 Fit 한다
    cost = criterion(hypothesis, X)  # 학습결과 평균제곱 오차값 cost를 연산
    cost.backward()       # 위 forward 연산 후, backward() cost를 연산   ( 텐서플로에 비해 추가 )
    optimizer.step()
    
    if step % 400 == 0:
        # 텐서플로는 출력 함수 결과가, 개별 인자와 tuple로 연결되어서 지정
        # pytorch 는 출력객체가 이미 특정이 되어 있어, 그 객체명만 그대로 지정하면 원하는 결과를 도출용이
        # (tensorflow에 비해 상당부분 생략)
        print(step,  cost.data.numpy(), model.weight.data.numpy(), model.bias.data.numpy())    

0 [ 11.50258541] [[-0.54821908]] [ 0.35482842]
400 [ 0.01583316] [[ 0.85420775]] [ 0.33142003]
800 [ 0.00230861] [[ 0.94432938]] [ 0.12655248]
1200 [ 0.00033662] [[ 0.97874218]] [ 0.048324]
1600 [  4.90814709e-05] [[ 0.99188274]] [ 0.01845242]
2000 [  7.15674241e-06] [[ 0.99690038]] [ 0.00704613]


In [7]:
# 학습모델이 잘 결과가 나왔는지를 Testing
predicted = model(Variable(torch.Tensor([[5]])))
predicted.data.numpy()

array([[ 4.99154806]], dtype=float32)

In [8]:
predicted = model(Variable(torch.Tensor([[2.5]])))
predicted.data.numpy()

array([[ 2.49929714]], dtype=float32)

In [9]:
predicted = model(Variable(torch.Tensor([[1.5],[3.5]])))
predicted.data.numpy()

array([[ 1.5023967 ],
       [ 3.49619746]], dtype=float32)

## Multi-variable Linear Regression (다항회귀식)

In [10]:
import torch
import torch.nn as nn
from torch.autograd import Variable
torch.manual_seed(777)   # for reproducibility

In [11]:
# X, Y tensor 데이터 정의
x_data = [[73., 80., 75.], [93., 88., 93.],
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

import pandas as pd
x = pd.DataFrame(x_data); y = pd.DataFrame(y_data); print(x,'\n', y)

      0     1      2
0  73.0  80.0   75.0
1  93.0  88.0   93.0
2  89.0  91.0   90.0
3  96.0  98.0  100.0
4  73.0  66.0   70.0 
        0
0  152.0
1  185.0
2  180.0
3  196.0
4  142.0


In [12]:
# 가설세우기 X1w + X2w + X3w +b
model = nn.Linear(3, 1, bias=True)
# cost criterion
criterion = nn.MSELoss()
# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [13]:
# Train the model
for step in range(2001):
    optimizer.zero_grad()
    # Our hypothesis
    hypothesis = model(X)
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 400 == 0:
        print(step, "Cost: ", cost.data.numpy(), "\nPrediction:", hypothesis.data.numpy())

0 Cost:  [ 44984.64453125] 
Prediction: [[-33.21160889]
 [-43.98809052]
 [-41.19184113]
 [-45.09777451]
 [-34.4379921 ]]
400 Cost:  [ 6.08452511] 
Prediction: [[ 154.57562256]
 [ 182.45509338]
 [ 181.54379272]
 [ 197.4908905 ]
 [ 138.4354248 ]]
800 Cost:  [ 4.96428204] 
Prediction: [[ 154.2260437 ]
 [ 182.69555664]
 [ 181.43769836]
 [ 197.40606689]
 [ 138.75782776]]
1200 Cost:  [ 4.0617342] 
Prediction: [[ 153.91270447]
 [ 182.91117859]
 [ 181.3427124 ]
 [ 197.32936096]
 [ 139.04754639]]
1600 Cost:  [ 3.33450747] 
Prediction: [[ 153.63189697]
 [ 183.10449219]
 [ 181.25769043]
 [ 197.25993347]
 [ 139.30792236]]
2000 Cost:  [ 2.74844885] 
Prediction: [[ 153.38027954]
 [ 183.27778625]
 [ 181.18159485]
 [ 197.197052  ]
 [ 139.54196167]]


In [14]:
# 학습모델 검증
predicted = model(Variable(torch.Tensor([[73., 80., 75.]])))
print('73., 80., 75. 의 경우', predicted.data.numpy())

73., 80., 75. 의 경우 [[ 153.37968445]]


## 파일을 활용하는 Linear Regression

In [15]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np
torch.manual_seed(777)   # for reproducibility

In [16]:
xy = np.loadtxt('./Lecture/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print("x_data Shape : ", x_data.shape,'\n', x_data[::5],'\nx_data  Length :', len(x_data))
print("\ny_data Shape : ", y_data.shape,'\n', y_data[::5], '\n\ndata type :', type(x_data))

x_data Shape :  (25, 3) 
 [[ 73.  80.  75.]
 [ 53.  46.  55.]
 [ 69.  70.  73.]
 [ 93.  89.  96.]
 [ 82.  86.  90.]] 
x_data  Length : 25

y_data Shape :  (25, 1) 
 [[ 152.]
 [ 101.]
 [ 141.]
 [ 192.]
 [ 177.]] 

data type : <class 'numpy.ndarray'>


In [17]:
# Pytorch 인식 가능한 형식변환 및 가설과 검증함수를 정의
x_data = Variable(torch.from_numpy(x_data))
y_data = Variable(torch.from_numpy(y_data))
# Our hypothesis XW+b
model = nn.Linear(3, 1, bias=True)
# cost criterion
criterion = nn.MSELoss()
# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [18]:
# Train the model
for step in range(2001):
    optimizer.zero_grad()
    # Our hypothesis
    hypothesis = model(x_data)
    cost = criterion(hypothesis, y_data)
    cost.backward()
    optimizer.step()

    if step % 400 == 0:
        print(step, "Cost: ", cost.data.numpy()[::5], 
              "\nPrediction:\n", hypothesis.data.numpy()[::5])

0 Cost:  [ 40526.734375] 
Prediction:
 [[-33.21160889]
 [-26.37543106]
 [-32.84194946]
 [-44.50363922]
 [-39.22988129]]
400 Cost:  [ 13.55295181] 
Prediction:
 [[ 155.51713562]
 [ 102.11494446]
 [ 143.29823303]
 [ 186.67991638]
 [ 175.20796204]]
800 Cost:  [ 11.30837631] 
Prediction:
 [[ 155.08659363]
 [ 102.61421204]
 [ 143.39726257]
 [ 186.99023438]
 [ 175.37065125]]
1200 Cost:  [ 9.73517418] 
Prediction:
 [[ 154.72688293]
 [ 103.03137207]
 [ 143.48040771]
 [ 187.2495575 ]
 [ 175.50772095]]
1600 Cost:  [ 8.63248825] 
Prediction:
 [[ 154.42637634]
 [ 103.37986755]
 [ 143.55021667]
 [ 187.4662323 ]
 [ 175.62330627]]
2000 Cost:  [ 7.85959053] 
Prediction:
 [[ 154.1754303 ]
 [ 103.67093658]
 [ 143.60884094]
 [ 187.64724731]
 [ 175.72076416]]


In [19]:
# Ask my score
print("Your score will be ", model(Variable(torch.Tensor([[100, 70, 101]]))).data.numpy())
print("Other scores will be ", model(Variable(torch.Tensor([[60, 70, 110], [90, 100, 80]]))).data.numpy())

Your score will be  [[ 181.31016541]]
Other scores will be  [[ 173.9997406 ]
 [ 179.72221375]]
