In [66]:
# np.array ( init ) : 1차원 배열데이터
# np.ndarray ( data type ) : 같은 종류만 담을 수 있는 배열데이터

In [73]:
import numpy as np

In [3]:
# np.array?

# 파이썬의 기본 array | 1. type("l"), 2. data
# np.array         | 1. type ( 타입 추정 ) 데이터를 보고 자동으로 타입을 넣어주는 기능
#                  | 2. data ( object == list, tuple, set )

# np.array 의 return => ndarray

In [4]:
arr = np.array([1, 2, 3, 4, 5])   # 함수
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)   # 자료형

numpy.ndarray

In [6]:
li = [1, 2, 3, 4, 5]

In [7]:
li

[1, 2, 3, 4, 5]

In [8]:
# arr, li => 동일한 데이터 / 동일한 데이터지만, 자료형 이 다른 두 개의 객체

In [9]:
len(li)
# elements 의 갯수

5

In [10]:
arr.shape

(5,)

In [11]:
arr.ndim

1

In [12]:
# ndim == len(shape)

In [13]:
arr = np.array([[1, 2], [3, 4]])

In [14]:
arr.shape

(2, 2)

In [15]:
arr.ndim

2

In [16]:
arr.itemsize   # Python array type ( "l":signed long; 4byte )

4

In [17]:
arr

array([[1, 2],
       [3, 4]])

In [18]:
arr.dtype   # 어떤 데이터 타입으로 저장할 것인가?
            # 데이터 추정/ 타입 추정 

dtype('int32')

In [19]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)  # explicit dtype

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr[0:2]   # 결과값 : ndarray

array([1, 2])

In [22]:
# 2 x 2 | array, list

# 1, 2
# 3, 4

In [23]:
li = [[1, 2],
      [3, 4],]

In [24]:
arr = np.array(li)

In [25]:
# 1. li, arr => [1, 2]  [3, 4] | arr[0], li[0] ( 두 개가 동일하게 indexing )
# 2. li, arr => 4              | li[1][1], arr[1][1], arr[1:1]
# 3. li, arr => [1, 3], [2, 4] | li (map), arr[:, 0]

In [26]:
# 4. elements 들에 동일한 연산을 수행하고 싶다. ( 제곱, double )

# [[2, 4],
# [6, 8]]  # double

# [[1, 4],
# [9, 16]]

# li 의 모양이 변경될 수 있다. ( 2차원; 2 x 3, 5 x 4 )

In [27]:
[
    [
        field * 2
        for field
        in row
    ]
    for row
    in li
]

[[2, 4], [6, 8]]

In [28]:
list(map(
    lambda row: list(map(lambda field: field * 2, row)),
    li,
))
arr ** 2

array([[ 1,  4],
       [ 9, 16]])

In [29]:
# 0. 전체 => 10
# 1. [4, 6]
# 2. [3, 7]       # li 에서 한번 구현 

In [30]:
# 전체 SUM 

result = 0   # initialize

for row in li:
    for field in row:
        # result += field
        result = result + field
        
result

10

In [31]:
from functools import reduce

In [32]:
reduce(
    lambda x,y: reduce(lambda a, b: a + b, x) +
        reduce(lambda a, b: a + b, y),
    li,  # x, y => row 하나하나 
)

# 2 x 2 => 100 x 300

10

In [33]:
li = [[1, 2,], [3, 4]]

In [34]:
# [3, 7]
# [4, 6]
li

[[1, 2], [3, 4]]

In [35]:
[
    # row[0] + row[1] + row[2] +... + row[n]
    reduce(lambda a,b: a + b, row)
    for row                            # row 단위로 쉽게 접근이 가능했기 때문에 
    in li
]

[3, 7]

In [36]:
print(arr)

[[1 2]
 [3 4]]


In [37]:
# init = [0, 0]      # fields ( 2칸 ; N 칸 )

init = [0 for i in range(len(li[0]))]
for rowIndex in range(len(li)):
    row = li[rowIndex]
    
    for fieldIndex in range(len(row)):
        field = row[fieldIndex]
        init[fieldIndex] += field   
init

[4, 6]

In [38]:
def temp_func(init, row):
    for fieldIndex in range(len(row)):
        init[fieldIndex] += row[fieldIndex]
    return init

reduce(
    temp_func,
    li,
    [0 for i in range(len(li[0]))],    # initialize
)

[4, 6]

In [39]:
# 10

print(arr)

[[1 2]
 [3 4]]


In [40]:
arr.sum()  # arr.sum()

10

In [41]:
print(arr)

[[1 2]
 [3 4]]


In [42]:
arr.sum(axis=0)

array([4, 6])

In [43]:
arr.sum(axis=1)

array([3, 7])

In [44]:
# Indexing

In [45]:
# 성적표 ( 학생 4명에 대한 국어, 영어, 수학 )

arr = np.array([
    [100, 100, 100],
    [60, 50, 30],
    [100, 90, 80],
    [80, 80, 90],
])

# 1. 학생들의 평균 점수를 구하고 싶다. [80, 70, 60.6, 85]
# 2. 평균 점수가 80점 + Filtering

In [46]:
# 순서를 바꾸는 방법

arr[  np.array([True, True, True, False])   ]

# map => Boolean Mask, Filtering Mask
# filter 

array([[100, 100, 100],
       [ 60,  50,  30],
       [100,  90,  80]])

In [47]:
# np.mean(arr, axis=1)
mean_arr = arr.mean(axis=1)

In [48]:
mean_arr
# [True, False, True, True]

# list(map(
#     lambda x: x >= 80,
#     mean_arr
# ))

mean_result = [
    x >= 80
    for x
    in mean_arr
]
mean_result = np.array(mean_result)

In [49]:
# mean_arr >= 80
# arr[mean_arr >= 80]

In [50]:
arr[   arr.mean(axis=1) >= 80   ]

array([[100, 100, 100],
       [100,  90,  80],
       [ 80,  80,  90]])

In [51]:
# 성적표 ( 학생 4명에 대한 국어, 영어, 수학 )

arr = np.array([
    [13, "안수찬1", 100, 100, 100],
    [14, "안수찬2", 60, 50, 30],
    [15, "안수찬3", 100, 90, 80],
    [16, "안수찬4", 80, 80, 90],
])

# 1. 학생들의 평균 점수를 구하고 싶다. [80, 70, 60.6, 85]
# 2. 평균 점수가 80점 + Filtering

In [52]:
# Numpy.ndarray => n-d array object. 동질의 데이터셋 

In [53]:
np.array(  arr[:, 2:]  , dtype=np.int64).mean(axis=1)

array([ 100.        ,   46.66666667,   90.        ,   83.33333333])

In [54]:
arr[ np.array(  arr[:, 2:]  , dtype=np.int64).mean(axis=1) >= 80 ]

array([['13', '안수찬1', '100', '100', '100'],
       ['15', '안수찬3', '100', '90', '80'],
       ['16', '안수찬4', '80', '80', '90']], 
      dtype='<U11')

In [55]:
arr = np.array(  arr[:, 2:] , dtype=np.int64 )

In [56]:
np.savetxt("arr.txt", arr, delimiter=",")

In [57]:
np.loadtxt("arr.txt", delimiter=",")

array([[ 100.,  100.,  100.],
       [  60.,   50.,   30.],
       [ 100.,   90.,   80.],
       [  80.,   80.,   90.]])

In [68]:
# 비디오 예매 서비스 ( netflix )
# 사용자(customer), 영화, 영화 actor, 렌탈, )

In [87]:
# data/payment.csv

In [88]:
import numpy as np

In [89]:
payment_arr = np.loadtxt("./data/payment.csv", delimiter=",")

ValueError: could not convert string to float: b'payment'

In [ ]:
payment_arr.ndim

In [ ]:
# column 0: customer_id
# column 1: amount ( 매출 ; 결제액 )

payment_arr.shape

In [ ]:
payment_arr[:5]

# 얼마만큼의 사용자가 있는가? 1 ... N번 => Unique 한 customer_id 의 배열 

In [ ]:
np.unique(  payment_arr[:, 0]  )

# 이걸 바탕으로 유저별 매출 !
# sorting 1: 119$, 2: 150$.... , => 우리 서비스에서 가장 많이 결제한 유저는 13번 

# sorting
# 1 => ______
# 2 => ______
# ndarray

In [ ]:
# Numpy !
# -------
# Selenium :: Web Browser
# os(Operating System), shutil(High-Level File Operator)
# --------
# Pandas

In [ ]:
# Indexing ( NxM 10:20, 3:5 )
# axis=0, 1
# Filtering Mask ( Broadcasting : 벡터 x 스칼라 )
# -----------------------
# For, List Comprehension, Lambda 

In [ ]:
# [
#     # row[0] + row[1] + row[2] +... + row[n]
#     reduce(lambda a,b: a + b, row)
#     for row                            # row 단위로 쉽게 접근이 가능했기 때문에 
#     in li
# ]

In [ ]:
li = [
    [1, 2, 3],
    [4, 5, 6],
]

def temp_func(a, b):
    print((a, b))
    return a + b

[
    reduce(temp_func, row)
    for row   # [1, 2, 3], [4, 5, 6]                            # row 단위로 쉽게 접근이 가능했기 때문에 
    in li
]

In [ ]:
reduce(lambda a, b: a + b, [1, 2, 3])

In [ ]:
# savetxt, loadtxt , np(.txt) 
# np.loadtxt, csv
payment_arr = np.loadtxt("./data/payment.csv", delimiter=",")

In [ ]:
payment_arr.shape

In [ ]:
payment_arr.ndim

In [ ]:
payment_arr[:5]

In [ ]:
# 1번 유저에 대한 그룹 ( Boolean Mask )
# [True, True, ...., False]

In [ ]:
payment_arr[:, 0] == 1

In [ ]:
# payment_arr[   payment_arr[:, 0] == 1   ]

In [ ]:
result = [
    [
        customer_id,
        payment_arr[   payment_arr[:, 0] == customer_id   ].sum()
    ]
    for customer_id 
    in np.unique(   payment_arr[:, 0]    )
]

In [ ]:
#np.array(result)

In [ ]:
# Numpy: 배열, N차원 배열, 벡터, 행렬

In [ ]:
# 2차원의 배열
a = np.array([
        [1, 2],
        [3, 4]
    ])

In [ ]:
b = np.array([
        [1, 0],
        [0, 1],
    ])

In [ ]:
# a 라는 행렬, b 라는 행렬 (E; 단위행렬) => a

In [ ]:
a * b                # Np.ndarray 연산 => Element 간의 연산 
                     # 행렬 모양 O, 행렬 처럼 쓰는 경우 +++

In [ ]:
np.dot(a, b)         # 행렬 간 연산 == 곱

In [ ]:
# 순차적의 숫자들의 리스트 

list(range(0, 10, 2))    # return range_generator

In [ ]:
# arange
np.arange(0, 10)

In [ ]:
# 1부터 10까지의 수 ( 10개 )
[i for i in range(1, 10 + 1)]

In [ ]:
[i + 1 for i in range(10)]

In [ ]:
list(range(1, 10 + 1))

In [ ]:
np.arange(1, 10 + 1)

In [ ]:
np.arange(10) + 1

In [ ]:
# 배열 ( 1로 초기화된 배열, 0으로 초기화된 배열 )

In [ ]:
np.ones(10)

In [ ]:
np.zeros(10)

In [ ]:
# np.ones((3, 3, 3, 3))

In [ ]:
# 1024 x 1024 x 3 == 1024 x 3072 ( shape )
# np.ones(100).reshape(10, 10)

In [ ]:
# #
# np.eye(10)

In [ ]:
# np.random.rand
# np.random.randn
# np.random.randint(100)

In [ ]:
# 주가에 대한 변화.

a = np.random.rand(4, 10) - 0.5

# 4개의 종목군에 대한 주가 변화량

In [ ]:
a

In [ ]:
# a.cumsum(axis=1)

In [ ]:
# 주가 => 랜덤한 그래프
# 모델링

In [ ]:
# pandas.Series, pandas.DataFrame

In [ ]:
# os, shutil

In [ ]:
import os

In [ ]:
# 1. 폴더 안에 있는 모든 파일의 리스트 보기

In [ ]:
os.listdir()                  # ls

In [ ]:
# 폴더 안에 있는 모든 엑셀 파일을 읽어서 ( == 모든 엑셀 파일을 찾자! )
# 이 데이터를 numpy.ndarray 로 만들자.

In [ ]:
[
    filename
    for filename
    in os.listdir()
    if filename.endswith(".ipynb")
]

In [ ]:
# 2. 폴더를 생성하고, 삭제하는 명령

In [ ]:
os.makedirs("happy")              # mkdir 

In [ ]:
os.rmdir("happy/")

# shutil ( == High-level File )

In [ ]:
# os.makedirs(), os.rmdir() 
# $ mkdir 
# $ rm       => 폴더를 recursive 하게 지우는 작업 
#             =>  ( rm -r ) 폴더 안에 파일이나 폴더가 있을 때 

In [ ]:
import shutil

In [ ]:
# shutil.rmtree("./happy/")   # rm -r

In [ ]:
# 폴더를 초기화하는 일 ...!


# if [ 폴더가 있는가? ]
#    [폴더를 삭제]
# [폴더를 생성]

In [ ]:
if "happy" in os.listdir():
    shutil.rmtree("happy")
os.makedirs("happy")

In [ ]:
# 파일 경로 

# .        | Current Dir
# ..       | Parent Dir
# ./, ../, ../../

In [ ]:
# np.loadtxt("./data/payment.csv", delimiter=",")

In [ ]:
os.path.join("a", "b", "c", "d.csv")

In [ ]:
os.path.join("..", "..", "data", "payment.csv")

In [ ]:
np.loadtxt(
    os.path.join("..", "..", "data", "payment.csv"),
    delimiter=",",
)

In [ ]:
# Jupyter - 데이터분석 위한 도구

In [ ]:
# %, _

In [ ]:
!ls

In [ ]:
!ls -al

In [ ]:
!rm -rf happy/

In [ ]:
!mkdir happy

In [ ]:
!ls

In [ ]:
# [filename for filename in !!ls]

In [ ]:
!!ls

In [ ]:
[filename for filename in _ if filename.endswith(".csv")]

In [ ]:
# Copy(복사), Move(이동)

In [ ]:
# # 복사 ( 파일을 읽어서, 그대로 다른 파일에 쓰는 )
# def copy(src, dest):
#     src_fp = open(src, "r")              # Readable => "r" => "rb"
#     dest_fp = open(dest, "w")
#     dest_fp.write(src_fp.read())
#     src_fp.close()
#     dest_fp.close()

In [ ]:
# Move

In [ ]:
# shutil.move

In [ ]:
!ls

In [ ]:
!cp arr.csv arr2.csv

In [ ]:
!ls

In [ ]:
!mv arr2.csv arr3.csv

In [ ]:
!ls

In [ ]:
# 한번에 주석처리 : Ctrl + "/" / CMD + "/"

In [ ]:
# 페이지에서 크로링/파싱
# 로그인 ( 입력폼을 찾아서, 텍스트 입력 )
# 클릭
# 자바스크립트를 강제적으로 실행

In [ ]:
# Selenium ( Test ) - IE, Firefox, Chrome, ..
#                         Firefox

In [ ]:
# 윈도우           = 설치가 안되는 라이브러리 O
#                => Python 3.X, 윈도우 사용자명 "한글" => "영어"
#                => virtualbox
#                => Numpy, Pandas ( O )

# Python 3.X ( + PATH )
# Jupyter Notebook
# Selenium

# 맥 ( 리눅스 )     = 설치가 다 되어야 O

# => 1. 소스코드를 받아서, 설치 ( .whl )
# => 2. pip install _________________   (O)
#     => pypi.., github...
# => 3. easy_install                    (X)
# => 4. anaconda ( conda install )      (X) - jupyter, numpy, pandas

# 리눅스 | pyenv, virtualenv, 


# 리눅스 ( CentOS, Redhat ) : yum install ______________
# 리눅스 ( Ubuntu  )        : apt-get install _____________
# 맥                       : brew install pyenv, pyenv-virtualenv